name: CI

on:
  push:
    paths:
      - "lib/**"
      - "android/**"
      - "ios/**"
      - "web/**"
      - "pubspec.yaml"

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'

    - name: Setup project
      run: |
        flutter pub get
        flutter pub run build_runner build

    - name: Lint and Analyze code
      run: |
        flutter format --set-exit-if-changed .
        flutter analyze .

    # - name: Run Tests
    #   run: flutter test

    - name: Build debug apk
      run: |
        flutter build apk --debug

        VERSION="v$(grep "flutter.versionName" android/local.properties | cut -d = -f 2)"
        cp build/app/outputs/flutter-apk/app-debug.apk "./Heartry-${VERSION}.apk"

        echo "Built apk for ${VERSION}"

    - uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: "*.apk"
